### ISSUE TITLE
Catch argument errors before upload

### ISSUE THREAD

**Issue by bjeavons** [ProboCI/probo-uploader#1]
I was receiving this response when trying to upload a asset.
`Upload failed. Error received from server:`

And thought it was indeed a server problem but turns out it was pebkac and that I had mistyped the token argument:

`probo-uploader -token=TOKEN ASSET` needed to be `--token`

probo-uploader should check for incorrect or missing token and not upload.

**Comment by Auspicus** [comment]
https://github.com/ProboCI/probo-uploader/blob/c130466e40585cd29caff48af79f33282b2de11e/bin/probo-uploader#L18

This line should catch the missing token option and throw an error. Since yargs (the package used to create CLI options) has updated they have deprecated the `demand` function in favor of `demandOption` and `demandCommand`. To fix this issue, we need to update this line to use one of these functions. We should also add a package-lock.json to make sure any future updates to the dependencies don't break the codebase.
